---
- name: Install Prezto
  git: repo=https://github.com/sorin-ionescu/prezto.git dest=~/.zprezto force=yes

- name: Symlink my dotfiles
  file: src=~/dotfiles/home/{{ item }}
        dest=~/{{ item }}
        state=link
        force=yes
  with_items:
    - .zshrc
    - .zpreztorc
    - .zshenv
    - .inputrc
    - .gitignore
    - .pythonrc
    - .gitconfig
