---
- name: Update packages
  become: yes
  become_method: sudo
  apt: upgrade=dist update_cache=yes

- name: Install libraries using APT
  apt: name={{ item }} state=latest
  become: yes
  become_method: sudo
  with_items:
    - ack-grep
    - bash
    - curl
    - git
    - htop
    - nmap
    - nodejs
    - mosh
    - most
    - python
    - python-pip
    # for FASD
    - python-pycurl
    - python3
    - vim
    - tmux
    - wget
    - zsh
    # Snap package manager
    - snapd
    - snapd-xdg-open
    - geany
    - aptitude
    - openssh-server
    - gadmin-openvpn-client
    # ZSH + agnoster theme
    - fonts-powerline
    # Android MTP
    - go-mtpfs
    # Other
    - xubuntu-restricted-extras
    # For byzanz + xrectsel
    - byzanz
    - autoconf
    - libx11-dev

- name: Change shell to ZSH root
  become: yes
  become_method: sudo
  user: shell=/bin/zsh name=root

- name: Change shell to ZSH current user
  become: yes
  become_method: sudo
  user: shell=/bin/zsh name={{ ansible_user }}

- name: Install FASD
  become: yes
  become_method: sudo
  copy: src=fasd dest=/usr/local/bin/fasd mode=755

- name: Check Snap exists
  stat: path=/run/snapd.socket
  register: snap_socket

- name: Install Snap packages (classic)
  command: "snap install --classic {{ item }}"
  register: snap_result
  changed_when: snap_result.rc != 0
  become: yes
  become_method: sudo
  with_items:
     - pycharm-professional
     - datagrip
     - slack
  when: snap_socket.stat.exists 
    
- name: Install Snap packages (jail)
  command: "snap install {{ item }}"
  register: snap_result
  changed_when: snap_result.rc != 0
  become: yes
  become_method: sudo
  with_items:
     - spotify
     - telegram-desktop
     - vlc
  when: snap_socket.stat.exists 
    
- name: Download fzf
  command: "git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf"

- name: fzf - install useful key bindings and fuzzy completion
  command: "~/.fzf/install --all"
