---
- name: Update Homebrew
  homebrew: update_homebrew=yes

- name: Tap fonts
  homebrew_tap: tap=caskroom/fonts state=present

- name: Install libraries with Homebrew
  homebrew: name={{ item }} state=latest
  with_items:
    - ack
    - awscli
    - curl
    - git
    - nmap
    - python
    - python3
    - readline
    - ssh-copy-id
    - watch
    - wget
    - zsh
    - httpie
    - tree
    - openssl
    - coreutils
    - findutils
    - mosh
    - cask
    - youtube-dl
    - htop
    - tmux
    - nano

- name: Install apps with Homebrew Cask
  homebrew_cask: name={{ item }} state=present
  with_items:
    - google-chrome
    - suspicious-package
    - vlc
    - xquartz
    - appcleaner
    - font-hack
    - iterm2

- name: Cleanup Brew packages
  command: brew cleanup
