#!/usr/bin/env bash

if [[ $EUID -eq 0 ]]; then
   echo "This script cannot be run as root" 
   exit 1
fi

if [[ `uname` == 'Linux' ]]; then
  ansible-playbook -i inventory ubuntu.yml
else
  ansible-playbook -i inventory osx.yml
fi
